# Generated by Django 4.1.4 on 2023-01-09 11:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_cart_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="specification",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
